### ISSUE TITLE
Too much logging

### ISSUE THREAD

**Issue by giddyhup** [kehangchen/node-red-contrib-sqldbs#2]
Even though I set Node RED's logging settings to 'error' I see for every database transaction an entry in my syslog.

**Comment by giddyhup** [comment]
I just noted that the database login is also being logged - including credentials.

**Comment by mdimai666** [comment]
@giddyhup use it
.node-red\node_modules\node-red-contrib-sqldbs\sqldbs.js

change
**this.logging = false;**
line ~30
`        this.connecting = false;
        this.dbname = n.db;
        this.dialect = n.dialect;

        this.logging = false;

        var node = this;

        function doConnect() {
`

**Comment by giddyhup** [comment]
Thanks.
